import json
import ssl
import urllib.request
import urllib.error
from typing import Dict, Any

from . import ImageAdapter
from .. import resolve_api_key_for, _proxy_addr_for, log

class GeminiImageAdapter(ImageAdapter):
    def generate(self, word: str, info: Dict[str, str], cfg: Dict[str, Any]) -> bytes:
        api_key = resolve_api_key_for("gemini", cfg)
        model_map = cfg.get("image_models", {}) or {}
        model = str(model_map.get("gemini", cfg.get("image_model", "gemini-2.5-flash-image")))
        base = "https://generativelanguage.googleapis.com/v1beta"
        url = f"{base}/models/{model}:generateContent"
        meaning = info.get("meaning", "")
        example = info.get("example", "")

        prompt = (
            f"Create a clear, memorable illustration to help an English learner remember the word '{word}'.\n\n"
            f"Word: {word}\n"
            f"Meaning: {meaning}\n"

            f"Step 1: Analyze the word’s category and choose the most fitting art style:\n"
            f"- If the word refers to a physical object (e.g., fruit, tool, animal): use **hyper-realistic product photography**.\n"
            f"- If it describes an abstract concept or emotion (e.g., honesty, boredom): use **surreal minimalist vector art**.\n"
            f"- If it's an action or a funny situation (e.g., stumble, giggle): use **3D cartoon (Pixar-style)**.\n"
            f"- If it's a nature term or vintage word (e.g., moss, quill): use **watercolor or hand-drawn sketch**.\n\n"

            f"Step 2: Visualize the sentence. Focus on the most concrete, visual aspect of the meaning sentence:\n"
            f"• Turn the sentence into a simple, thumbnail-friendly scene with one central subject.\n"
            f"• Use colors, shapes, and objects to suggest the tone and meaning of the word.\n\n"

            f"CRITICAL RULES:\n"
            f"- DO NOT include any text, letters, numbers, or word labels in the image.\n"
            f"- Keep the composition simple and centered: high contrast, easy to understand at small size.\n"
            f"- Make the image emotionally aligned with the sentence's tone (serious, humorous, warm, etc.).\n"
            f"- Use only one main subject; avoid busy or cluttered backgrounds.\n\n"

            f"Output only the scene (no captions)."
        )

        payload = {
            "contents": [{"parts": [{"text": prompt}]}]
        }
        body = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(url, data=body, method="POST")
        req.add_header("Content-Type", "application/json")
        req.add_header("x-goog-api-key", api_key)
        proxy = _proxy_addr_for("gemini", cfg)
        ctx = ssl.create_default_context()
        https_handler = urllib.request.HTTPSHandler(context=ctx)
        log(f"[image] gemini request url={url} prompt={prompt}")
        try:
            if proxy:
                proxy_handler = urllib.request.ProxyHandler({"http": proxy, "https": proxy})
                opener = urllib.request.build_opener(proxy_handler, https_handler)
                resp = opener.open(req, timeout=120)
            else:
                opener = urllib.request.build_opener(https_handler)
                resp = opener.open(req, timeout=120)
        except urllib.error.HTTPError as e:
            try:
                err_body = e.read().decode("utf-8", errors="ignore")
            except Exception:
                err_body = "<no body>"
            log(f"[image] gemini HTTPError {e.code}: {err_body}")
            raise
        log(f"[image] gemini response {resp.status} {resp.reason}")
        raw = resp.read().decode("utf-8")
        log(f"[image] gemini response raw={raw}")
        data = json.loads(raw)
        log(f"[image] gemini response data={data}")
        parts = []
        try:
            parts = data["candidates"][0]["content"]["parts"]
        except Exception:
            parts = []
        b64 = ""
        for p in parts:
            try:
                inline = p.get("inline_data") or p.get("inlineData") or {}
                b64 = inline.get("data", "")
                if b64:
                    break
            except Exception:
                pass
        if not b64:
            raise RuntimeError("gemini image generation: missing inline image data")
        import base64
        img_bytes = base64.b64decode(b64)
        log(f"[image] gemini generated bytes length={len(img_bytes)}")
        return img_bytes