import json
import ssl
import urllib.request
import urllib.error
from typing import Dict, Any

from . import ImageAdapter
from .. import resolve_api_key_for, _proxy_addr_for, log

class GeminiImageAdapter(ImageAdapter):
    def generate(self, word: str, info: Dict[str, str], cfg: Dict[str, Any]) -> bytes:
        api_key = resolve_api_key_for("gemini", cfg)
        model_map = cfg.get("image_models", {}) or {}
        model = str(model_map.get("gemini", cfg.get("image_model", "gemini-2.5-flash-image")))
        base = "https://generativelanguage.googleapis.com/v1beta"
        url = f"{base}/models/{model}:generateContent"
        meaning = info.get("meaning", "")
        prompt = (
            f"Create an illustration to help remember the English word '{word}' (meaning: {meaning}). "
            f"First, analyze the 'vibe' of the word to decide the art style: "
            f"1. For concrete objects (e.g., fruit, tools), use 'Hyper-realistic product photography' style. "
            f"2. For abstract concepts or emotions (e.g., freedom, thought), use 'Surrealist minimal vector' style. "
            f"3. For actions or funny situations (e.g., jump, clumsy), use 'Exaggerated 3D Pixar-style cartoon'. "
            f"4. For nature or vintage terms, use 'Watercolour' or 'Hand-drawn sketch' style. "
            f"\n"
            f"Make the image focused on a single subject. "
            f"CRITICAL RULES: NO text, NO letters, NO numbers. Keep the composition simple, high contrast, and identifiable at a small size (thumbnail friendly)."
        )
        payload = {
            "contents": [{"parts": [{"text": prompt}]}]
        }
        body = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(url, data=body, method="POST")
        req.add_header("Content-Type", "application/json")
        req.add_header("x-goog-api-key", api_key)
        proxy = _proxy_addr_for("gemini", cfg)
        ctx = ssl.create_default_context()
        https_handler = urllib.request.HTTPSHandler(context=ctx)
        log(f"[image] gemini request url={url} prompt={prompt}")
        try:
            if proxy:
                proxy_handler = urllib.request.ProxyHandler({"http": proxy, "https": proxy})
                opener = urllib.request.build_opener(proxy_handler, https_handler)
                resp = opener.open(req, timeout=120)
            else:
                opener = urllib.request.build_opener(https_handler)
                resp = opener.open(req, timeout=120)
        except urllib.error.HTTPError as e:
            try:
                err_body = e.read().decode("utf-8", errors="ignore")
            except Exception:
                err_body = "<no body>"
            log(f"[image] gemini HTTPError {e.code}: {err_body}")
            raise
        log(f"[image] gemini response {resp.status} {resp.reason}")
        raw = resp.read().decode("utf-8")
        log(f"[image] gemini response raw={raw}")
        data = json.loads(raw)
        log(f"[image] gemini response data={data}")
        parts = []
        try:
            parts = data["candidates"][0]["content"]["parts"]
        except Exception:
            parts = []
        b64 = ""
        for p in parts:
            try:
                inline = p.get("inline_data") or p.get("inlineData") or {}
                b64 = inline.get("data", "")
                if b64:
                    break
            except Exception:
                pass
        if not b64:
            raise RuntimeError("gemini image generation: missing inline image data")
        import base64
        img_bytes = base64.b64decode(b64)
        log(f"[image] gemini generated bytes length={len(img_bytes)}")
        return img_bytes